[package]
name = "hieroglyph"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.28"
image = "0.25.2"
resvg = "0.44.0"
twemoji-assets = "1.3.0"
unicode-segmentation = "1.12.0"
unicode-normalization = "0.1.24"
