[package]
name = "hieroglyph"
version = "0.1.0"
edition = "2021"

[dependencies]
resvg = "0.44.0"
twemoji-assets = "1.3.0"
unicode-segmentation = "1.12.0"
cosmic-text = "0.12.1"

[dev-dependencies]
image = "0.25.2"
