[tasks.build-fonts]
install_crate = { crate_name = "rust-script" }
command = "rust-script"
args = ["scripts/build_fonts.rs"]

[tasks.fmt]
run_task.name = [
  "cargo-fmt",
  "scripts-fmt",
  "templates-fmt",
]

[tasks.cargo-fmt]
command = "cargo"
args = ["fmt"]
toolchain = "nightly"

[tasks.scripts-fmt]
command = "rustfmt"
args = ["scripts/build_fonts.rs"]
toolchain = "nightly"

[tasks.templates-fmt]
command = "rustfmt"
args = ["templates/fonts.template.rs"]
toolchain = "nightly"
