[package]
name = "package"
edition = "2024"

[[bin]]
name = "package"
path = "main.rs"

[dependencies]
zstd.workspace = true
tar.workspace = true
glob.workspace = true
anyhow.workspace = true
indicatif.workspace = true
